version: 2
updates:
  - package-ecosystem: "npm"
    directories: [/]
    schedule:
      interval: "daily"
    allow:
      - dependency-type: "production"
    ignore:
      - dependency-name: "axios"